---
# tasks file for gym

- name: Install SublimeText
  include_role:
    name: sublime

# - name: Install PyBullet dependencies
#   apt:
#     state: present
#   with_items:
#     - build-essential
#     - autoconf
#     - libtool 
#     - pkg-config 
#     - python-opengl 
#     - python-imaging 
#     - python-pyrex 
#     - python-pyside.qtopengl 
#     - idle-python2.7 
#     - qt4-dev-tools 
#     - qt4-designer 
#     - libqtgui4 
#     - libqtcore4 
#     - libqt4-xml 
#     - libqt4-test 
#     - libqt4-script 
#     - libqt4-network 
#     - libqt4-dbus 
#     - python-qt4 
#     - python-qt4-gl 
#     - libgle3 
#     - python-dev
#     - python3-setuptools

# - name: Install PyBullet
#   pip:
#     state: latest
#     name: PyBullet
#     extra_args: -U --no-cache-dir

- name: Install gym dependency
  apt:
    state: present
    name: python3-setuptools

- name: Install OpenAI gym
  pip:
    state: latest
    executable: pip3
    name: gym
