---
# tasks file for sublime

- name: Install GPG keys for SublimeText
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Add repository and install SublimeText
  include_role:
    name: package_installer