---

- name: Install common software properties
  apt:
    state: latest
    name: software-properties-common

- name: ubuntu | ensuring Ubuntu universe repo is enabled ({{ ansible_distribution_version }} >= 16.04)
  apt_repository:
    repo: "deb http://us.archive.ubuntu.com/ubuntu bionic universe"
    update_cache: yes
    state: present
    validate_certs: no


- name: install pip
  apt:
    state: latest
    name: python-pip

- name: install pip3
  apt:
    state: latest
    name: python3-pip

- name: Install Python development library
  apt:
    state: latest
    name: python3-dev

- name: Install git
  apt:
    state: latest
    name: git